title: Longitudinal study of robots.txt files
description: Different annual statistics of the Common Crawl robots.txt web archives

show_navigation: True
navlist:
  - title: Overview
    url: /
  - title: File statistics
    url: /file-statistics
  - title: Top user agents
    url: /top-user-agents
  - title: User agent bias
    url: /user-agent-bias
  - title: Resources
    url: /resources

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
